[mcp_servers]
content = '''
{
    "mcpServers": {
        "example-stdio-mcp-name": {
            "transport": "stdio", 
            "command": "uv/npx", 
            "args": ["script"]
        },
        "example-tcp-mcp-name": {
            "transport": "streamable_http",
            "url": "http://mcp-server:port/mcp"
        }
     }
}
'''

# Major Agent and Sub Agents
# don't add tools to major agent, add tools to sub agents.
[model_config]
[model_config.major_agent]
    model_name = ""
    api_key = ""
    base_url = ""
    system_prompt = '''
    '''
[model_config.sub_agent_1]
    model_name = ""
    api_key = ""
    base_url = ""
    system_prompt = '''
    '''
    mcp_tools = ["example-stdio-mcp-name", "..."]
    inside_tools = ["..."]
[model_config.sub_agent_2]
    model_name = ""
    api_key = ""
    base_url = ""
    system_prompt = '''
    '''
    mcp_tools = ["example-tcp-mcp-name", "..."]
    inside_tools = ["..."]

# Tavily API Key
[tavily_config]
tavily_api_key = ""

# Prompt Templates
[prompt_templates]

[prompt_templates.init]
prompt = '''

'''

[prompt_templates.example]
args = ["example_arg1", "example_arg2"]
prompt = '''
use {example_arg1} and {example_arg2} to ...
'''